name: crucible-ci

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - LICENSE
      - '**.md'

  workflow_dispatch:

jobs:
  generate-job-matrix-parameters:
    runs-on: ubuntu-latest
    outputs:
      userenvs: ${{ steps.get-userenvs.outputs.userenvs }}
      endpoints_github: ${{ steps.get-endpoints-github.outputs.endpoints }}
    steps:
    - name: checkout crucible-ci
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci
    - name: checkout rickshaw
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/rickshaw
        ref: master
        path: rickshaw
    - name: run get-userenvs
      id: get-userenvs
      uses: ./crucible-ci/.github/actions/get-userenvs
      with:
        rickshaw-directory: "./rickshaw"
    - name: run get-endpoints-github
      id: get-endpoints-github
      uses: ./crucible-ci/.github/actions/get-endpoints
      with:
        runner-type: "github"

  display-job-matrix-parameters:
    runs-on: ubuntu-latest
    needs: generate-job-matrix-parameters
    steps:
    - name: Echo generate-job-matrix-parameters outputs
      run: echo "${{ toJSON(needs.generate-job-matrix-parameters.outputs) }}"

  crucible-ci-github-runners:
    runs-on: ubuntu-latest
    needs:
    - generate-job-matrix-parameters
    - display-job-matrix-parameters
    strategy:
      fail-fast: false
      matrix:
        endpoint: ${{ fromJSON(needs.generate-job-matrix-parameters.outputs.endpoints_github) }}
        userenv: ${{ fromJSON(needs.generate-job-matrix-parameters.outputs.userenvs) }}
    steps:
    - name: Matrix Parameters => (${{ matrix.endpoint }}, ${{ matrix.userenv }})
      run: |
        echo "endpoint=${{ matrix.endpoint }}"
        echo "userenv=${{ matrix.userenv }}"
    - name: checkout bench-fio
      uses: actions/checkout@v2
      with:
        path: bench-fio
    - name: checkout crucible-ci
      uses: actions/checkout@v2
      with:
        repository: perftool-incubator/crucible-ci
        ref: main
        path: crucible-ci
    - name: run crucible-ci->integration-tests
      uses: ./crucible-ci/.github/actions/integration-tests
      with:
        artifact_tag: "crucible-ci-github-runners__${{ matrix.endpoint }}-${{ matrix.userenv }}"
        ci_endpoint: "${{ matrix.endpoint }}"
        scenarios: "fio"
        userenvs: "${{ matrix.userenv }}"
        run_samples: 3
        repeat_runs: "yes"
        ci_target: "fio"
        ci_target_dir: ${{ github.workspace }}/bench-fio

  crucible-ci-complete:
    runs-on: ubuntu-latest
    needs:
    - crucible-ci-github-runners
    steps:
    - name: Confirm Success
      run: echo "crucible-ci-complete"
